export class Ticket{
    TicketId:string;
    FlightId:string;
    Title:String;
    FirstName:string;
    LastName:string;
    AgeGroup:string;
    SourceId:String;
    DestinationId:string;
    DepartTime:string;
    ArrivalTime:string;
    Duration:string;
    SeatNo:string;
    DateTravel:Date;
    Class:string;
    Price:number;
    BookingId:string;
    DateCancellation:Date;   
    constructor(TicketId,FlightId,Title,FirstName,LastName,AgeGroup,
        SourceId,
        DestinationId,
        DepartTime,
        ArrivalTime,
        Duration,
        SeatNo,
        DateTravel,
        Class,
        Price,
        BookingId)
        {
            this.TicketId=TicketId;
            this.FlightId=FlightId;
            this.Title=Title;
            this.FirstName=FirstName;
            this.LastName=LastName;
            this.AgeGroup=AgeGroup;
            this.SourceId=SourceId;
            this.DestinationId=DestinationId;
            this.DepartTime=DepartTime;
            this.ArrivalTime=ArrivalTime;
            this.Duration=Duration;
            this.SeatNo=SeatNo;
            this.DateTravel=DateTravel;
            this.Class=Class;
            this.Price=Price;
            this.BookingId=BookingId;
            this.DateCancellation=null;
        }
}